### ISSUE TITLE
Confusion related to audiotools package.

### ISSUE THREAD

**Issue by cwitkowitz** [audacitorch/pyharp#2]
When I was following the tutorial in the README, I attempted to `pip install audiotools`, but ran into the following error:
```
Collecting audiotools
  Downloading audiotools-0.1.0.tar.gz (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 1.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8sta_obr/audiotools_c732ce749cf54c81ab1d70b711f38bf9/setup.py", line 7, in <module>
          with open(path.join(here, 'README.md'), encoding='utf-8') as f:
        File "/home/rockstar/anaconda3/envs/test/lib/python3.10/codecs.py", line 906, in open
          file = builtins.open(filename, mode, buffering)
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-8sta_obr/audiotools_c732ce749cf54c81ab1d70b711f38bf9/README.md'
      [end of output]
```
I was not aware that `audiotools` was third-party software (https://github.com/descriptinc/audiotools), and originally did not investigate further since the **README link was broken**.

After this realization, I was able to successfully install with `pip install git+https://github.com/descriptinc/audiotools`. We may want to **make this more clear in the README**.

**Comment by cwitkowitz** [comment]
Fixed by PR https://github.com/audacitorch/pyharp/pull/10 ...

**Comment by oreillyp** [comment]
Closed after merge
